- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: 12345678901-compute@developer.gserviceaccount.com
    credentials_file: /opt/ansible/inventory/service-account.json
    project_id: ansible-123456
    machine_type: f1-micro
    image: centos-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
